# Generated by Django 2.2.5 on 2019-10-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(0, '男'), (1, '女')], default=1, max_length=12, verbose_name='性别'),
        ),
    ]
