# Generated by Django 2.2.5 on 2019-10-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191009_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', help_text='60*60', null=True, upload_to='avatar', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('0', '男'), ('1', '女')], default='1', max_length=12, verbose_name='性别'),
        ),
    ]
