# Generated by Django 2.2.5 on 2019-10-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191009_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.png', help_text='60*60', null=True, upload_to='avatar', verbose_name='头像'),
        ),
    ]
